# Master role
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-infra-chrony
  labels:
    machineconfiguration.openshift.io/role: infra
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - path: /etc/chrony.conf
          contents:
            source: data:text/plain;charset=utf-8;base64,${CHRONY_CONF_B64}
          mode: 0644
          user:
            name: root
          group:
            name: root
