apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: infra
spec:
  machineConfigSelector:
    matchExpressions:
      - values:
          - worker
          - infra
        operator: In
        key: machineconfiguration.openshift.io/role
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/infra: ""
