apiVersion: v1
baseDomain: cloud-priv.si.orange.es
proxy:
  httpProxy: "http://10.13.14.200:8080"
  httpsProxy: "http://10.13.14.200:8080"
  noProxy: "cloud-priv.si.es,10.13.170.0/23,10.13.176.0/22,10.13.172.0/22"
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    MIIG4TCCBMmgAwIBAgITIQAACro9jwrMJMkJXwAAAAAKujANBgkqhkiG9w0BAQsF
    ADBdMRcwFQYKCZImiZPyLGQBGRYHZnRncm91cDESMBAGCgmSJomT8ixkARkWAmVz
    MRYwFAYKCZImiZPyLGQBGRYGY29zbW9zMRYwFAYDVQQDEw1jZXJ0UEtJc3ViUHJv
    MB4XDTIwMTAwODA4MzA1MVoXDTI1MTAwNzA4MzA1MVowQjEgMB4GA1UEChMXQ0xP
    VUQtUFJJVi5TSS5PUkFOR0UuRVMxHjAcBgNVBAMTFUNlcnRpZmljYXRlIEF1dGhv
    cml0eTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAJcFjTkIhCF7vBQp
    o8pRhpeE/+zeIPoFtl5cewPG0xg3ISn/28wvOeexMq49ngItcIlYl83IRkjm6210
    Vl6/Ygr2eQTbpv26jTvUGxqXtiuV2pmc60pZ9mey3SlTUCW8MjryDg/ADytsSn9K
    4xPaxG3BYuKBq19/UhNEaAKv19tQZMbNlMqpViupGujYYyxVpqxVqOak8NZuZ5YT
    TfuzoOTzEjI/5aRzyXftA3ZFE4u/wU3+L8DSrSy76qMz49yU3IDyZCvg5kmvQ21/
    rKpVnAvoUh+qFqRJJX+evZ3Vubjb+hGLJ0bNHIPgHKhNn74/7HHKbNn5dEGrlm6e
    pIyRYwcXoaDh8sfKlqjOEdusnQGjSN6oM26pEd5GVA6Di+wD0e65YOgHCtCkLJon
    PAjqUtMkQd2slw3JaJXnGub4sdSe4I0CKU3AZNv/sw9FRQ9nH4J+RvMsagMLTBqn
    gcjRXOrNrufs2BGVOjnONeMypAJjkix8OYV2r05qzX9vQ/JX5wIDAQABo4ICMzCC
    Ai8wDwYDVR0TAQH/BAUwAwEB/zALBgNVHQ8EBAMCAYYwHQYDVR0OBBYEFCrBnAGA
    B8L0EzwPphmREAxTD+q7MB8GA1UdIwQYMBaAFOYxFa151Xh/XpmGP8yWVrsoKOzk
    MIHQBgNVHR8EgcgwgcUwgcKggb+ggbyGgblsZGFwOi8vL0NOPWNlcnRQS0lzdWJQ
    cm8sQ049TVlFQzg1UEtJMTA0UCxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2Vy
    dmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1lcyxEQz1mdGdy
    b3VwP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1j
    UkxEaXN0cmlidXRpb25Qb2ludDCBvgYIKwYBBQUHAQEEgbEwga4wgasGCCsGAQUF
    BzAChoGebGRhcDovLy9DTj1jZXJ0UEtJc3ViUHJvLENOPUFJQSxDTj1QdWJsaWMl
    MjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERD
    PWVzLERDPWZ0Z3JvdXA/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNl
    cnRpZmljYXRpb25BdXRob3JpdHkwOwYJKwYBBAGCNxUHBC4wLAYkKwYBBAGCNxUI
    hpnRc5OreYSlhw+shyKCwsMcS4Ttjn2FjL1GAgFkAgECMA0GCSqGSIb3DQEBCwUA
    A4ICAQALKvCRLFC1Ssu2CACZxmh/WqIYbAmBcKP4+73FfPsG3WVOQm/7sReWTIk5
    HfnES4ecADAdls/q0+tcxZg/18fVahW43GnP534yVdh4gjThzRsh/rCPmrWwSdFT
    zRDgZDQzmARlvkp8ihWfv2cDKClaMPRxiN33PcMxWqU+mYOEAYf7lgOikm+PLRON
    /mxoWzWlXSmmpnWAnN5/rlxU1tMaLW6TzHKk8RcmQgVNZAeGpyLErrckxvUv37si
    fyh84CSSod4MkcpeTh19wd60xQeStoWwoP+KJr9e6R3exO4exP1R/uFNp4p7i3hn
    p4ThiNwgdPu2l+Svz977ksraPMXa2XaFHoTavgdSjBc1rEIaC5nigjO5tn/G6+Pd
    pCFypw2tmcNHriAVrknVFOrn5AqCnPyv3HBFL5T4nGADQZ6PFBeXaYgO6Qz8yzbJ
    IiQvo1t4j97Ywwztu2Bra17aLHPTaXs4EnL7iluwjv02xzS2kvYVL9FdoCVs1TB8
    1W0EsBqsZnNkCOMdkjW0CQ/HR3qtGHT6Uk6VBngS/N7cX5LC6iLKFAK1/Nm3Av0X
    rUxCEwDXO/iDNat+w36V6iilUY8iKQ2ghgjRVrF7r39BnfRETpMNTQ1LOqGkEemS
    AjMzPV4vQekgwMXwiXTIRAzOHgk3SSRV9TCUjHFgxnxlFdawDQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIHhTCCBW2gAwIBAgITRgAAAALr0SOWLUWHtAAAAAAAAjANBgkqhkiG9w0BAQsF
    ADBaMRcwFQYKCZImiZPyLGQBGRYHZnRncm91cDESMBAGCgmSJomT8ixkARkWAmVz
    MRYwFAYKCZImiZPyLGQBGRYGY29zbW9zMRMwEQYDVQQDEwpjZXJ0UEtJUHJvMB4X
    DTE2MDIxNjEzMjIyNVoXDTM2MDIxMTEzMjIyNVowXTEXMBUGCgmSJomT8ixkARkW
    B2Z0Z3JvdXAxEjAQBgoJkiaJk/IsZAEZFgJlczEWMBQGCgmSJomT8ixkARkWBmNv
    c21vczEWMBQGA1UEAxMNY2VydFBLSXN1YlBybzCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAJlenZRjDgxOVaxEfR9Oe2giKQvmKuSRYVcEP7lzRigr4SMi
    nJz8XkHuYgP/uB/UIgNgyn36PenIJ0IgLPz2bw+LW4UC8Zf/DvwxZunm9rrh/HTj
    qquHNeQbntOZ0p1SlFHVhXnQSTC+uNbQj7Ka1z8YPmaTaELVSAJy3Ejb7EUbfoAe
    Tl3RBPjEhRQMdluKtFSwNF2nV8S+uB8hDljfAw25cWdahiDXGXLtrvxvhrCAMsan
    mimwVI5s908G7VM6sFgQn3mDhpG0NeqFGdMXfqEtzKpeCw0A4HzLoD20EQrV6HvP
    4CsVeUm0rZ9lc4yvmLr1Hv4lKcEyCvPZ1kmkKyZEUl5nIP9pqvhi2nIhXMjJym5G
    xaKy0aqBK2bIYYlvctog20UJOUgY9Bc5bjogqbZtZqSKvpUtlGB0+pVMY/1kJnjO
    ftwf3oVv5QrVqlD1pUNIB1zKK9auAjcQ3u7Nkg3ii3353jEO1HGDNhn4vmMtZ9dT
    MR1QxZoM/qhTdkGJJKdOzoRF0UyhZHuTduGNnzHSi0QrZnxydGv5TvAwuTuwJVWc
    l2z9nZe5Kt+SOLgydNPRYMfg5eu2q31aClrwKku8xEZtscTxM4dw5+8xQYtAPIi3
    EB5yu02cl6QgST3N0TvraCgR3MSF/t1GC0vSa0ZSahUs7c+s3Mf2Dh8ZBHzbAgMB
    AAGjggI/MIICOzAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQU5jEVrXnVeH9e
    mYY/zJZWuygo7OQwOwYJKwYBBAGCNxUHBC4wLAYkKwYBBAGCNxUIhpnRc5OreYSl
    hw+shyKCwsMcS4O9zVSH9ewrAgFkAgEFMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8E
    BTADAQH/MB8GA1UdIwQYMBaAFOQ8PjeXfs3Foy1+bJRt6DAGPCD7MIHNBgNVHR8E
    gcUwgcIwgb+ggbyggbmGgbZsZGFwOi8vL0NOPWNlcnRQS0lQcm8sQ049TVlFQzg1
    UEtJMTAzUCxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vy
    dmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1lcyxEQz1mdGdyb3VwP2NlcnRpZmlj
    YXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRp
    b25Qb2ludDCBuwYIKwYBBQUHAQEEga4wgaswgagGCCsGAQUFBzAChoGbbGRhcDov
    Ly9DTj1jZXJ0UEtJUHJvLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
    cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWVzLERDPWZ0Z3JvdXA/
    Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRo
    b3JpdHkwDQYJKoZIhvcNAQELBQADggIBAINYO3CDLG3MSmtklNvXRxd4uLC7ztjj
    979BnOpB2A/gGjMK3nTdIdMVRa6oZ1o20t2Zs3yqtVktZJmom3SWkxqY77Wqv8gR
    zooRFmGuCV529lF1H+rc+smVtHsVYKqge1TJrfRJKajl92JxmvQJ2IYsuufxcsaF
    uQNWnU4X7SqbGoDWqrSo5q0xqY/OxjI1LwotRuDL5follZ5ENfS/sy+qw9R+Yiu8
    2bBa8ftdNz+2G/kwyFlSxrzbk3WtpxJWLxHIoOMh57WKFkrbQ5eSxSKJwCoQC7w/
    gG7pcURfZZjzmldEybSspfW4/qXvlsgx3sZ74pk989aH9jJPtZXS7tLlmItJEpct
    7Ichq44aikSjrtYVwsFOsoqZFqNlFaC8wiZJCnSI8X7wt9imST9A0zrGJ+4pPKWJ
    w4BDU4mfN9ybwpj2DJ5UY3HATDVuSa4N2dSq26KNj/chgsQum79K54K2bjonnxwb
    fX75d/hKGx+RTgHZPTKI2B8RmNkr9bldF9ap3/3KiAFyV/ccBElPtUi3xzhlpKIS
    49P/zdYyn/6/8gBGD0G+RWz00cMvt3t/Aqf8k0PzgV4ub8LJkY1/ERtaO9OI6Wkj
    Z7XYY8+uy/frnsV3tJaBeGpyzc1LWLkcchVTEzLK4jIG9dgEXrLnEfCZcCqeLBFB
    N3qAL0+sfIBA
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFpDCCA4ygAwIBAgIQVE5iQOHDBb5EzqujCrN3QDANBgkqhkiG9w0BAQsFADBa
    MRcwFQYKCZImiZPyLGQBGRYHZnRncm91cDESMBAGCgmSJomT8ixkARkWAmVzMRYw
    FAYKCZImiZPyLGQBGRYGY29zbW9zMRMwEQYDVQQDEwpjZXJ0UEtJUHJvMB4XDTE2
    MDIxNTE2MzExNVoXDTQ2MDIxNTE2NDExNFowWjEXMBUGCgmSJomT8ixkARkWB2Z0
    Z3JvdXAxEjAQBgoJkiaJk/IsZAEZFgJlczEWMBQGCgmSJomT8ixkARkWBmNvc21v
    czETMBEGA1UEAxMKY2VydFBLSVBybzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBAMqqj2ja1vynu/M8haNIJH0tGqDY/PePWqQ9dH+0sKvAbN+9em74E8nY
    +/5WmhEstqnopIMzhMDXCNcNI/IbR/tKgE7Pn11Pzo0zqba7RZrERQWOmF2VRZvh
    bYddmdeWBefaEq5OlL18TqMV1KBy98Tx6AummdMiTMxyg+2X1ayem6ilczWwS4eC
    X7p4Bc80QeCCtSbFbZN99un7HjXZkR5fjeeDN9AzFY+xaGHBqfoi1TkKhZ5PgEym
    t+fTGmVU07jPsUepXC/8stg8268tZOwATGw77uuaw3I42F+U9UtwCLjte6FUYY+y
    vsmMlY8E4kmeTYNUI2dlh6YURj39i0kN7Imj5sGf3Z2XpJian2zGGOoh8Xkn5QZM
    U5n/ReFOuD2Tt7vBb2C7aFJxMhJz+/j8ifHmZMijBtCrI93ymC+OpcwogoccDaNd
    5HykEA46VPdKjUAI/dw2+J1/3cbRqCAg+DHw5Zp1uGk6WRx/S9vw+Oyno3FpG4CL
    lhETc0yfuOyMAKyi+4XlIej1TX5ZG6/tNmQckWD2NFaVQ2Xa13Y3QvX5pAMx7kVE
    IDC1dPd0Y7Regk+NzNQf6kYHKlA2K7FwiI4npqFpu55mq2Z6NQhCKL5K9VHFRkJD
    4bS6FSnEZ9mQOoyAuTht2OUzajpwwn1Z8mUU81XPxevoFVJMe4eZAgMBAAGjZjBk
    MBMGCSsGAQQBgjcUAgQGHgQAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTAD
    AQH/MB0GA1UdDgQWBBTkPD43l37NxaMtfmyUbegwBjwg+zAQBgkrBgEEAYI3FQEE
    AwIBADANBgkqhkiG9w0BAQsFAAOCAgEAAztnGdDH6c8LMnOOJhWMW9GDr8j1om2p
    TkiudgwQIYNgCFxrSYKWahtaZJYoHx24R1taXOhTH/2A+WQt++21CIZhoiG1Ggxd
    PtvdWNOT8bbXf2aWpWwhba/lCJf0TVrJRLDjBX8ItIxI+SFPkTGiwCpYK0uAY93/
    WXaOlXchnMvaWT7TCzjtJjYDmmXfHt3sG6eawCrr43Ql2O70XTqzMQfYrXCmJjs+
    te20jyrc0K8PBpJODmzU8gHDHWhFCYHNRTEwAnybHU8Tbyv2GkbrHbAVC8865tR0
    zclYOjvlF53nIjV1pPhYc6VeHq0iUr4oErGTDmWxe0kdOBk4ebdMSchBrpKix2Qf
    Pt+gmeDCmlLWCVuawltRjPRF260wXwHDPjW4VFxqg9EJk6Z1rCsKGkSodRPYgorz
    QfZW3P+ekmTv8P9/gfePq+rFYcSJiCa+MFwFPY4zr3YEbRurSlBh0DvyzANAvaCf
    vwwd+exKi27mNzoZyJijOa+VvpufJ7qiKQWLfa3BmdK22/9GDewGXA3vxWW3W/rj
    gk8L57oKRiM9i9VKUO30urbPljjEfQ/itaoz8xKJVhvFRu6lxZrRgBEXPa2KD8Vj
    yLA6n+r3AAmORfFE0XcpW86o8LJxH9Lr6modsdEyUskadnKEo8gH+P/Qx04aNSo9
    g7XC4Oue8iQ=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFpDCCA4ygAwIBAgIQVE5iQOHDBb5EzqujCrN3QDANBgkqhkiG9w0BAQsFADBa
    MRcwFQYKCZImiZPyLGQBGRYHZnRncm91cDESMBAGCgmSJomT8ixkARkWAmVzMRYw
    FAYKCZImiZPyLGQBGRYGY29zbW9zMRMwEQYDVQQDEwpjZXJ0UEtJUHJvMB4XDTE2
    MDIxNTE2MzExNVoXDTQ2MDIxNTE2NDExNFowWjEXMBUGCgmSJomT8ixkARkWB2Z0
    Z3JvdXAxEjAQBgoJkiaJk/IsZAEZFgJlczEWMBQGCgmSJomT8ixkARkWBmNvc21v
    czETMBEGA1UEAxMKY2VydFBLSVBybzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBAMqqj2ja1vynu/M8haNIJH0tGqDY/PePWqQ9dH+0sKvAbN+9em74E8nY
    +/5WmhEstqnopIMzhMDXCNcNI/IbR/tKgE7Pn11Pzo0zqba7RZrERQWOmF2VRZvh
    bYddmdeWBefaEq5OlL18TqMV1KBy98Tx6AummdMiTMxyg+2X1ayem6ilczWwS4eC
    X7p4Bc80QeCCtSbFbZN99un7HjXZkR5fjeeDN9AzFY+xaGHBqfoi1TkKhZ5PgEym
    t+fTGmVU07jPsUepXC/8stg8268tZOwATGw77uuaw3I42F+U9UtwCLjte6FUYY+y
    vsmMlY8E4kmeTYNUI2dlh6YURj39i0kN7Imj5sGf3Z2XpJian2zGGOoh8Xkn5QZM
    U5n/ReFOuD2Tt7vBb2C7aFJxMhJz+/j8ifHmZMijBtCrI93ymC+OpcwogoccDaNd
    5HykEA46VPdKjUAI/dw2+J1/3cbRqCAg+DHw5Zp1uGk6WRx/S9vw+Oyno3FpG4CL
    lhETc0yfuOyMAKyi+4XlIej1TX5ZG6/tNmQckWD2NFaVQ2Xa13Y3QvX5pAMx7kVE
    IDC1dPd0Y7Regk+NzNQf6kYHKlA2K7FwiI4npqFpu55mq2Z6NQhCKL5K9VHFRkJD
    4bS6FSnEZ9mQOoyAuTht2OUzajpwwn1Z8mUU81XPxevoFVJMe4eZAgMBAAGjZjBk
    MBMGCSsGAQQBgjcUAgQGHgQAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTAD
    AQH/MB0GA1UdDgQWBBTkPD43l37NxaMtfmyUbegwBjwg+zAQBgkrBgEEAYI3FQEE
    AwIBADANBgkqhkiG9w0BAQsFAAOCAgEAAztnGdDH6c8LMnOOJhWMW9GDr8j1om2p
    TkiudgwQIYNgCFxrSYKWahtaZJYoHx24R1taXOhTH/2A+WQt++21CIZhoiG1Ggxd
    PtvdWNOT8bbXf2aWpWwhba/lCJf0TVrJRLDjBX8ItIxI+SFPkTGiwCpYK0uAY93/
    WXaOlXchnMvaWT7TCzjtJjYDmmXfHt3sG6eawCrr43Ql2O70XTqzMQfYrXCmJjs+
    te20jyrc0K8PBpJODmzU8gHDHWhFCYHNRTEwAnybHU8Tbyv2GkbrHbAVC8865tR0
    zclYOjvlF53nIjV1pPhYc6VeHq0iUr4oErGTDmWxe0kdOBk4ebdMSchBrpKix2Qf
    Pt+gmeDCmlLWCVuawltRjPRF260wXwHDPjW4VFxqg9EJk6Z1rCsKGkSodRPYgorz
    QfZW3P+ekmTv8P9/gfePq+rFYcSJiCa+MFwFPY4zr3YEbRurSlBh0DvyzANAvaCf
    vwwd+exKi27mNzoZyJijOa+VvpufJ7qiKQWLfa3BmdK22/9GDewGXA3vxWW3W/rj
    gk8L57oKRiM9i9VKUO30urbPljjEfQ/itaoz8xKJVhvFRu6lxZrRgBEXPa2KD8Vj
    yLA6n+r3AAmORfFE0XcpW86o8LJxH9Lr6modsdEyUskadnKEo8gH+P/Qx04aNSo9
    g7XC4Oue8iQ=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIHhTCCBW2gAwIBAgITRgAAAALr0SOWLUWHtAAAAAAAAjANBgkqhkiG9w0BAQsF
    ADBaMRcwFQYKCZImiZPyLGQBGRYHZnRncm91cDESMBAGCgmSJomT8ixkARkWAmVz
    MRYwFAYKCZImiZPyLGQBGRYGY29zbW9zMRMwEQYDVQQDEwpjZXJ0UEtJUHJvMB4X
    DTE2MDIxNjEzMjIyNVoXDTM2MDIxMTEzMjIyNVowXTEXMBUGCgmSJomT8ixkARkW
    B2Z0Z3JvdXAxEjAQBgoJkiaJk/IsZAEZFgJlczEWMBQGCgmSJomT8ixkARkWBmNv
    c21vczEWMBQGA1UEAxMNY2VydFBLSXN1YlBybzCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAJlenZRjDgxOVaxEfR9Oe2giKQvmKuSRYVcEP7lzRigr4SMi
    nJz8XkHuYgP/uB/UIgNgyn36PenIJ0IgLPz2bw+LW4UC8Zf/DvwxZunm9rrh/HTj
    qquHNeQbntOZ0p1SlFHVhXnQSTC+uNbQj7Ka1z8YPmaTaELVSAJy3Ejb7EUbfoAe
    Tl3RBPjEhRQMdluKtFSwNF2nV8S+uB8hDljfAw25cWdahiDXGXLtrvxvhrCAMsan
    mimwVI5s908G7VM6sFgQn3mDhpG0NeqFGdMXfqEtzKpeCw0A4HzLoD20EQrV6HvP
    4CsVeUm0rZ9lc4yvmLr1Hv4lKcEyCvPZ1kmkKyZEUl5nIP9pqvhi2nIhXMjJym5G
    xaKy0aqBK2bIYYlvctog20UJOUgY9Bc5bjogqbZtZqSKvpUtlGB0+pVMY/1kJnjO
    ftwf3oVv5QrVqlD1pUNIB1zKK9auAjcQ3u7Nkg3ii3353jEO1HGDNhn4vmMtZ9dT
    MR1QxZoM/qhTdkGJJKdOzoRF0UyhZHuTduGNnzHSi0QrZnxydGv5TvAwuTuwJVWc
    l2z9nZe5Kt+SOLgydNPRYMfg5eu2q31aClrwKku8xEZtscTxM4dw5+8xQYtAPIi3
    EB5yu02cl6QgST3N0TvraCgR3MSF/t1GC0vSa0ZSahUs7c+s3Mf2Dh8ZBHzbAgMB
    AAGjggI/MIICOzAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQU5jEVrXnVeH9e
    mYY/zJZWuygo7OQwOwYJKwYBBAGCNxUHBC4wLAYkKwYBBAGCNxUIhpnRc5OreYSl
    hw+shyKCwsMcS4O9zVSH9ewrAgFkAgEFMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8E
    BTADAQH/MB8GA1UdIwQYMBaAFOQ8PjeXfs3Foy1+bJRt6DAGPCD7MIHNBgNVHR8E
    gcUwgcIwgb+ggbyggbmGgbZsZGFwOi8vL0NOPWNlcnRQS0lQcm8sQ049TVlFQzg1
    UEtJMTAzUCxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vy
    dmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1lcyxEQz1mdGdyb3VwP2NlcnRpZmlj
    YXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRp
    b25Qb2ludDCBuwYIKwYBBQUHAQEEga4wgaswgagGCCsGAQUFBzAChoGbbGRhcDov
    Ly9DTj1jZXJ0UEtJUHJvLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
    cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWVzLERDPWZ0Z3JvdXA/
    Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRo
    b3JpdHkwDQYJKoZIhvcNAQELBQADggIBAINYO3CDLG3MSmtklNvXRxd4uLC7ztjj
    979BnOpB2A/gGjMK3nTdIdMVRa6oZ1o20t2Zs3yqtVktZJmom3SWkxqY77Wqv8gR
    zooRFmGuCV529lF1H+rc+smVtHsVYKqge1TJrfRJKajl92JxmvQJ2IYsuufxcsaF
    uQNWnU4X7SqbGoDWqrSo5q0xqY/OxjI1LwotRuDL5follZ5ENfS/sy+qw9R+Yiu8
    2bBa8ftdNz+2G/kwyFlSxrzbk3WtpxJWLxHIoOMh57WKFkrbQ5eSxSKJwCoQC7w/
    gG7pcURfZZjzmldEybSspfW4/qXvlsgx3sZ74pk989aH9jJPtZXS7tLlmItJEpct
    7Ichq44aikSjrtYVwsFOsoqZFqNlFaC8wiZJCnSI8X7wt9imST9A0zrGJ+4pPKWJ
    w4BDU4mfN9ybwpj2DJ5UY3HATDVuSa4N2dSq26KNj/chgsQum79K54K2bjonnxwb
    fX75d/hKGx+RTgHZPTKI2B8RmNkr9bldF9ap3/3KiAFyV/ccBElPtUi3xzhlpKIS
    49P/zdYyn/6/8gBGD0G+RWz00cMvt3t/Aqf8k0PzgV4ub8LJkY1/ERtaO9OI6Wkj
    Z7XYY8+uy/frnsV3tJaBeGpyzc1LWLkcchVTEzLK4jIG9dgEXrLnEfCZcCqeLBFB
    N3qAL0+sfIBA
    -----END CERTIFICATE-----

compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    openstack:
      type: m1.worker
      additionalNetworkIDs:
      - 61ded1c3-9e21-4a45-9b7d-b91d4370a099
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    openstack:
      type: m1.master
  replicas: 3
metadata:
  creationTimestamp: null
  name: tor01-aot-009
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    apiVIP: 10.0.0.5
    cloud: overcloud
    computeFlavor: m1.worker
    externalDNS: null
    externalNetwork: floating-pre
    ingressVIP: 10.0.0.7
    lbFloatingIP: 10.132.172.75
    apiFloatingIP: 10.132.172.53
    octaviaSupport: "0"
    region: ""
    trunkSupport: "1"
    clusterOSImage: "http://10.134.171.104/rhcos-openstack.x86_64.qcow2.gz"
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2RwYXJrZXNyZWRoYXRjb20xbHV3b2hxdWNvazM5bXRpbnlwdTR3cWJpMWk6V0w1SUhWSDY2QjEzVjBNS1MxMlExMlMxMjFES0ZBUEdTSVEzMjlLQUJGM0M0UU1XVkJIRFYzN01TTkc2M1lFVQ==","email":"dparkes@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2RwYXJrZXNyZWRoYXRjb20xbHV3b2hxdWNvazM5bXRpbnlwdTR3cWJpMWk6V0w1SUhWSDY2QjEzVjBNS1MxMlExMlMxMjFES0ZBUEdTSVEzMjlLQUJGM0M0UU1XVkJIRFYzN01TTkc2M1lFVQ==","email":"dparkes@redhat.com"},"registry.connect.redhat.com":{"auth":"NTExMTAwNTl8dWhjLTFMVXdPaHFVQ29rMzlNVElOeXBVNHdRQmkxSTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPR0V5WXpjMFptUmlPVEkwT1dWaE9XVTFOemc0TkRRMU16TTJaakEyWXlKOS53amNTZ1FWREJDZGVBMWk0Z2g4Y1gtRmdxbzlObEJKSFdNMTEySjFOYU4xNzk5ZElQVnRXaE5FUkdmbzVvMng3Qm9id0xUT1hlQzJFS0FjZmR6X296Wl9ia3pvS29oOXBnd1BYNVhpd2pQZnlfR1FzY09OTkxjM216VE5nZWVlZzRUR0wyT1JTWkZnMEc3TU9vWWR0d2JqZFJPc3AwczEyeDRaWEdQTmVoR096MEVDTkdGRWdqa0F0Z1BRbVRaa3hDX0R2N3E1TUQyaXpmX0NhWmVQOFozZXhydlF5TldxOEVVb2o1YXpjTHlKeTB2ZnBrNDdTcEhSWlNvMEpEVm16ZVpoX3BZbGJQbUdkTjd6WGNGX3Z1SmcxUVh6YTViSXdXNTFjcy1tODFxbFRKRXl0aTRKejM0bUxleGlZZllvU095OVZOSmRTYi1DX1pvdVlLdjVuR2o1NUpEYnZNT0hHdHFYdmdldXlTTWVIcmIyZGlpUm15cEk2WXc4a1plbFZnbGozUFpsV29kUlNQeXA5dTExVjJsZ0FZR2x4c2xWazYwSl93NEE1a1VOa2plNnNKZHhnYW5KYVh6cmJmRjVKMWRXeFNOanh6TzRwd1FDdEVSbUR5eFBnSms1eDZiZ2tVSzlBYjBpZjVfZGtTSnI0YXNzTGo3NDlxUzloWHJqVXAxcVZHbURsblhUMUdwcFotVEFWU0tXQU9Kb3RSdnVZX1J1OEZYOUIteVJ6b0Vyd0lHSWJ2UnVJOU1rYk5PSVZFMFpEUWpMeVpVa2o3eVNuOTQzc0VTQmR1OFBoTnpPMjc3a0RPZmtQN2xCZVhFcjBRblhiMG81b181SVFheUdqWUlrMXRna2VtQkFHbHN4NHlRYXJNUEg4TkZzQUk1N1VVcmdtWVo2eDhjMA==","email":"dparkes@redhat.com"},"registry.redhat.io":{"auth":"NTExMTAwNTl8dWhjLTFMVXdPaHFVQ29rMzlNVElOeXBVNHdRQmkxSTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPR0V5WXpjMFptUmlPVEkwT1dWaE9XVTFOemc0TkRRMU16TTJaakEyWXlKOS53amNTZ1FWREJDZGVBMWk0Z2g4Y1gtRmdxbzlObEJKSFdNMTEySjFOYU4xNzk5ZElQVnRXaE5FUkdmbzVvMng3Qm9id0xUT1hlQzJFS0FjZmR6X296Wl9ia3pvS29oOXBnd1BYNVhpd2pQZnlfR1FzY09OTkxjM216VE5nZWVlZzRUR0wyT1JTWkZnMEc3TU9vWWR0d2JqZFJPc3AwczEyeDRaWEdQTmVoR096MEVDTkdGRWdqa0F0Z1BRbVRaa3hDX0R2N3E1TUQyaXpmX0NhWmVQOFozZXhydlF5TldxOEVVb2o1YXpjTHlKeTB2ZnBrNDdTcEhSWlNvMEpEVm16ZVpoX3BZbGJQbUdkTjd6WGNGX3Z1SmcxUVh6YTViSXdXNTFjcy1tODFxbFRKRXl0aTRKejM0bUxleGlZZllvU095OVZOSmRTYi1DX1pvdVlLdjVuR2o1NUpEYnZNT0hHdHFYdmdldXlTTWVIcmIyZGlpUm15cEk2WXc4a1plbFZnbGozUFpsV29kUlNQeXA5dTExVjJsZ0FZR2x4c2xWazYwSl93NEE1a1VOa2plNnNKZHhnYW5KYVh6cmJmRjVKMWRXeFNOanh6TzRwd1FDdEVSbUR5eFBnSms1eDZiZ2tVSzlBYjBpZjVfZGtTSnI0YXNzTGo3NDlxUzloWHJqVXAxcVZHbURsblhUMUdwcFotVEFWU0tXQU9Kb3RSdnVZX1J1OEZYOUIteVJ6b0Vyd0lHSWJ2UnVJOU1rYk5PSVZFMFpEUWpMeVpVa2o3eVNuOTQzc0VTQmR1OFBoTnpPMjc3a0RPZmtQN2xCZVhFcjBRblhiMG81b181SVFheUdqWUlrMXRna2VtQkFHbHN4NHlRYXJNUEg4TkZzQUk1N1VVcmdtWVo2eDhjMA==","email":"dparkes@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDmCEZPF7iyGeB6R9Spy3jZboOomTuFLtzJn2QRU/i7O0IfeiogUrKE0u3FGg1ksGWbwKxna82sABNoq2Sx0SdRjb0TBcL7Cr5yPYnK2QX68oqKsR2uK7rBmbnagTqaxkUY/JTRFH2DFiQhYc2dHhzhR431T48f/w5mxVFbMUETmQ== root@krklxprospdir002.cloud-priv.si.orange.es

