apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-example
  labels:
    app: pv-example
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
