apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-example
  labels:
    app: rbd-write-workload-generator-cache
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
